# Generated by Django 4.1.7 on 2023-03-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'NEBULOSA'), ('ESTRELA', 'ESTRELA'), ('GALÁXIA', 'GALÁXIA'), ('PLANETA', 'PLANETA')], default='', max_length=100),
        ),
    ]
