# Generated by Django 4.1.7 on 2023-03-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
